print("What did you grt when you cross a snowman with a vampire?")
input()
print("frostbite")
input()
print("A black hole!")
input()
print("knock..knock")
input()
print("who is there")
input()
print("intturepting cow.")
input()
print("interrupting cow wh",end="")
print("-moo!")
